### ISSUE TITLE
Negative yield (A)

### ISSUE THREAD

**Issue by jaytlennon** [LennonLab/Growth_Curves#11]
Seems that with some data sets (including "test") return negative values for yield parameter (A). If positive, the values would seem to be plausible. It is also peculiar that the negative yield parameter which is presumably used to plot predicted values, seems to do a good job of fitting observed data. cc: @mmuscarella @vkuo2 @wrshoemaker

**Comment by wrshoemaker** [comment]
This could potentially be solved by using a MLE optimization algorithm that allows for parameter values to be constrained. For example, use the [L-BFGS-B](https://en.wikipedia.org/wiki/Limited-memory_BFGS#L-BFGS-B) algorithm instead of BFGS. This can be done in the `mle` function in the [bblme](https://cran.r-project.org/web/packages/bbmle/bbmle.pdf) R package. For example,

`fit <- mle2(loglikelihood, method="L-BFGS-B", lower=c(ymax=0)`

where you get a MLE where ymax has to be greater than or equal to zero.  

I just did this in Python and got a reasonable fit to the data.
![a2](https://cloud.githubusercontent.com/assets/7355399/26215516/99525ff8-3bce-11e7-8b87-84cad3544eb3.png)

with the following parameter estimates:

b0 (intercept) = 0.0933328
A = 0.13328121
umax = 0.03122032
lambda = 1.71307104

The fit might not be perfect, but at least the parameters can easily be interpreted cc: @mmuscarella @vkuo2 @jaytlennon

**Comment by jaytlennon** [comment]
@wrshoemaker @mmuscarella @vkuo2:

Thanks to Will for suggestion. I tried changing the method to `L-BFGS-B`.  I also added the `lower =C...` statement. The output parameters for the `growth.modGomp("../data/Pseudo.csv", "csv_test", synergy=F, temp=F, smooth=F)` in test.example.R are identical. 

Make me wonder if the `lower=c(=ymax))` statement is correct/working. We're trying to constrain `A` to positive values, so I tried that as well, and got no differences in parameter output.  

I don't see other places in `bin` where we would need to make changes to script. Here's what I was playing around with:

    # Perform grid.mle2 Fits
    fit1<-grid.mle2(minuslogl=s.trim~dnorm(mean=m.gomp(t.trim,c(b0,A,umax,L)),
                    sd=exp(z)),grids=grids1,start=start1,data=tmpdata,
                    method="L-BFGS-B", lower=c(ymax))

No pull requests being made

**Comment by jaytlennon** [comment]
@wrshoemaker @mmuscarella @vkuo2 

If we choose to troubleshoot, perhaps we can use a common dataset. The one that I've been most recently working with is `Pseudo.csv` in the "data" folder of "Growth_Curves" repo; also attached here as .txt
[Pseudo.txt](https://github.com/LennonLab/Growth_Curves/files/1017166/Pseudo.txt)

**Comment by wrshoemaker** [comment]
@jaytlennon `lower=c(ymax)` is just an example of how to use the argument. You'd have to change the variable names. @vkuo2 expressed interest in modifying Mario's code to include lower bounds. Would you be willing to get the `lower` argument working in R, @vkuo2?

**Comment by jaytlennon** [comment]
@wrshoemaker Yes, I tried with `lower=c(A)` and still got negative values for A. cc: @vkuo2 @mmuscarella

**Comment by mmuscarella** [comment]
@jaytlennon can you provide a snippet of code that is providing the negative result

**Comment by mmuscarella** [comment]
A2-B3 in the output from `growth.modGomp("../data/Pseudo.csv", "csv_test", synergy=F, temp=F, smooth=F)` correct?

**Comment by jaytlennon** [comment]
@mmuscarella I'm not entirely sure what is generating the negative A parameter values, but they were arising in a number of datasets, including test datasets, along with recoding in Python. @wrshoemaker suggested it was due to non-linear regression algorithm getting stuck in local minima, which seems reasonable. He indicated that he fixed using the L-BFGS-B command. I assume this was in them modified.gompertz file, but perhaps not: 

# Perform grid.mle2 Fits
    fit1<-grid.mle2(minuslogl=s.trim~dnorm(mean=m.gomp(t.trim,c(b0,A,umax,L)),
                    sd=exp(z)),grids=grids1,start=start1,data=tmpdata,
                    method="BFGS")
    print("finished fit", quote=F)

**Comment by mmuscarella** [comment]
I think I figured out one potential problem. To fit the data just to the max growth (no death phase), we trimmed the data. This means that for well A2 in Pseudo.csv we end up with only 5 data points. But we are trying to fit a model with 5 free parameters. As such, the we are not finding good minima in the fit. I'm not sure why this would result into negative fits for the A parameter, but I think we need to make sure we have more data points than free parameters before we continue.

**Comment by mmuscarella** [comment]
I don't understand the output though because all of the curves look really good

**Comment by jaytlennon** [comment]
OK, that's a good point @mmuscarella regarding number of obs relative to parameters. I haven't tried this in the last few days, but I seem to recall that we were getting negative values for other data sets, too, which presumably had more observations. 

I totally agree with your previous response. That is, we plot the raw data. Then we plot the fits which are based on the parameters and modified Gompertz equation. If the the A parameter is wonky (i.e. negative) then the fits should not look good. 

This make me wonder if it's just something about how the parameters are being exported. For example, the absolute values of the reported A values are believable.

**Comment by mmuscarella** [comment]
Ok I think fixed this for now. I'm not sure if my solution is the best, but it works. I should point out that when A was negative, b0 was large. There seems to be an interaction between the two in the function `b0+A*exp(-exp(umax*exp(1)*(L-t)/A+1))`. We can plot this and explore parameter space to see if there is a way to make more appropriate modifications. But for now I just forced A to be the absolute value of the parameter given. This makes the mle fit really bad when A is negative because the large b0.

**Comment by jaytlennon** [comment]
@mmuscarella Thanks. Not sure whether we should "close" the issue. But I ran the new code and the fits seem good (not any better than before), but importantly yield non-negative parameter values. 

One thing I wonder about is the <5 observation issue. In the Pseudo.csv example, we actually had eight observations. This is because we were doing this in the Klett flask by hand and because the strains were fairly fast growing. Three of the later observations were post A max (i.e., entering death phase), so perhaps the time series is truncated down to ~5 or less. Something to keep in mind for future?

cc: @wrshoemaker @vkuo2

**Comment by mmuscarella** [comment]
The comments. I was wrong, the model is only fitting 4 parameters. The z parameter is actually a variance term. 

But you are correct, the data is truncated. This is because the current model does not fit the death phase and thus will have a bad fit due to the slow at the end. There is another version of this model that Colin started working on and it is included in the repo but it never had good results. Also, the meaning of some of the terms became complicated with the new model (i.e. A was no longer the max density).

**Comment by mmuscarella** [comment]
We are now constraining the best model fit to only select values of A that are positive
